name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 20 * * *" # 每天北京时间凌晨 4:00 自动运行
  workflow_dispatch:     # 支持在 Actions 页面手动点击 "Run workflow" 随时一键同步

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'iDvel/rime-ice' }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: iDvel/rime-ice
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false
